site_name: distributed cloud ML 
nav:
    - Home: index.md
    - Getting Started:
        - Connecting to Raspberry Pi: getting-started/setting-up-pi.md
    - Cameras:
        - Using the PiCamera: camera/picamera.md
        - Webcam video/image: camera/webcam.md
    - Vision System:
        - Character Recognition: vision/character.md
    - Speech Recognition:
        - Deepspeech: speech/deepspeech.md
        - Sphinx: speech/sphinx.md
        - Text to Speech: speech/text-to-speech.md
    - Mapping:
        - Lidar SLAM: mapping/lidar-slam.md
    - iRobot:
        - Keyboard Control: irobot/keyboard.md
    - ASPLOS 2018: asplos2018/real-time.md
    - People: people/people.md
theme: readthedocs
