site_name: distributed cloud ML 
nav:
    - Home: index.md
    - Getting Started:
        - Connecting to Raspberry Pi: getting-started/setting-up-pi.md
    - Using the PiCamera: picamera.md
    - Speech Recognition:
        - Deepspeech: speech/deepspeech.md
theme: readthedocs
